/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_COMMUNICATION_THRUSTER_COMMAND_PB_H_INCLUDED
#define PB_COMMUNICATION_THRUSTER_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _communication_Thrust {
    double thrust;
} communication_Thrust;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define communication_Thrust_init_default        {0}
#define communication_Thrust_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */
#define communication_Thrust_thrust_tag          1

/* Struct field encoding specification for nanopb */
#define communication_Thrust_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   thrust,            1)
#define communication_Thrust_CALLBACK NULL
#define communication_Thrust_DEFAULT NULL

extern const pb_msgdesc_t communication_Thrust_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define communication_Thrust_fields &communication_Thrust_msg

/* Maximum encoded size of messages (where known) */
#define COMMUNICATION_THRUSTER_COMMAND_PB_H_MAX_SIZE communication_Thrust_size
#define communication_Thrust_size                9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
